CREATE SCHEMA IF NOT EXISTS NBA24_25;

CREATE TABLE NBA24_25.NBATEAMS(
    TEAM_ID VARCHAR(20) PRIMARY KEY,
    FULL_NAME VARCHAR(50) NOT NULL,
    ABBREVIATION VARCHAR(10) NOT NULL,
    NICKNAME VARCHAR(20) NOT NULL,
    YEAR_FOUNDED INT,
    TEAM_URL_LOGO TEXT NOT NULL
);

CREATE TABLE NBA24_25.NBA_GAMES(
    GAME_ID VARCHAR(20)PRIMARY KEY,
    GAME_DATE DATE NOT NULL
);

CREATE TABLE NBA24_25.NBA_TEAM_STATES(
    TEAM_ID VARCHAR(20)PRIMARY KEY REFERENCES NBA24_25.NBATEAMS(TEAM_ID),
    TEAM_STATE VARCHAR(20) NOT NULL
);

CREATE TABLE NBA24_25.NBA_TEAM_CITY(
    TEAM_ID VARCHAR(20) PRIMARY KEY REFERENCES NBA24_25.NBATEAMS(TEAM_ID),
    TEAM_CITY VARCHAR(20) NOT NULL
);

CREATE TABLE NBA24_25.ACTIVE_NBA_PLAYERS(
    PLAYER_ID VARCHAR(20) PRIMARY KEY,
    TEAM_ID VARCHAR(20) NOT NULL REFERENCES NBA24_25.NBATEAMS(TEAM_ID),
    PLAYER_LAST_NAME VARCHAR(20),
    PLAYER_FIRST_NAME VARCHAR(20),
    JERSEY_NUMBER VARCHAR(5),
    POSITION VARCHAR(20),
    PLAYER_HEIGHT VARCHAR(20),
    PLAYER_WEIGHT VARCHAR(20),
    COLLEGE VARCHAR(40),
    COUNTRY VARCHAR(50),
    DRAFT_YEAR SMALLINT,
    DRAFT_ROUND SMALLINT,
    DRAFT_NUMBER SMALLINT,
    PTS NUMERIC(5,3),
    REB NUMERIC(5,3),
    AST NUMERIC(5,3),
    PLAYER_PICTURE_URL TEXT NOT NULL
);

CREATE TABLE NBA24_25.NBA_GAMES_TEAM_STATS(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25.NBA_GAMES(GAME_ID),
    TEAM_ID VARCHAR(20) REFERENCES NBA24_25.NBATEAMS(TEAM_ID),
    WL VARCHAR(10),
    MIN INT,
    FGM SMALLINT,
    FGA SMALLINT,
    FG3M SMALLINT,
    FG3A SMALLINT,
    FTM SMALLINT,
    FTA SMALLINT,
    OREB SMALLINT,
    DREB SMALLINT,
    AST SMALLINT,
    STL SMALLINT,
    BLK SMALLINT,
    PF SMALLINT,
    PLUS_MINUS SMALLINT,
    PRIMARY KEY (GAME_ID, TEAM_ID)
);

-- Originally was the string for away and home team
CREATE TABLE NBA24_25.HOME_VISITING_TEAM(
    GAME_ID VARCHAR(20) PRIMARY KEY REFERENCES NBA24_25.NBA_GAMES(GAME_ID),
    HOME_TEAM_ID VARCHAR(20) NOT NULL REFERENCES NBA24_25.NBATEAMS(TEAM_ID),
    VISITING_TEAM_ID VARCHAR(20) NOT NULL REFERENCES NBA24_25.NBATEAMS(TEAM_ID) 
);

-- Only tracks made shots when the score changes
CREATE TABLE NBA24_25.PLAY_BY_PLAY_SCORE(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25.NBA_GAMES(GAME_ID),
    CURRENT_PERIOD SMALLINT,
    TIME_LEFT VARCHAR(25),
    HTM_PTS INT,
    VTM_PTS INT,
    PRIMARY KEY(GAME_ID, CURRENT_PERIOD, TIME_LEFT,HTM_PTS,VTM_PTS) 
);


CREATE TABLE NBA24_25.BOXSCORES(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25.NBA_GAMES(GAME_ID),
    PLAYER_ID VARCHAR(20) REFERENCES NBA24_25.ACTIVE_NBA_PLAYERS(PLAYER_ID),
    STARTER SMALLINT,
    PLAYED SMALLINT,
    ASSISTS SMALLINT,
    BLOCKS SMALLINT,
    BLOCKS_RECEIVED SMALLINT,
    FGM SMALLINT,
    FGA SMALLINT,
    FOULS_OFFENSIVE SMALLINT,
    FOULS_DRAWN SMALLINT,
    FOULS_PERSONAL SMALLINT,
    FOULS_TECHNICAL SMALLINT,
    FTM SMALLINT,
    FTA SMALLINT,
    MINUTES_PLAYED VARCHAR(20),
    PLUS_MINUS SMALLINT,
    POINTS_FAST_BREAK SMALLINT,
    POINTS_IN_PAINT SMALLINT,
    POINTS_SECOND_CHANCE SMALLINT,
    OREB SMALLINT,
    DREB SMALLINT,
    STL SMALLINT,
    FG3M SMALLINT,
    FG3A SMALLINT,
    TURNOVERS SMALLINT,
    FG2M SMALLINT,
    FG2A SMALLINT,
    HOMEORAWAY VARCHAR(5),
    PRIMARY KEY (GAME_ID, PLAYER_ID)
);


CREATE TABLE NBA24_25.INJURY_REPORT(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25.NBA_GAMES(GAME_ID),
    PLAYER_ID VARCHAR(20) REFERENCES NBA24_25.ACTIVE_NBA_PLAYERS(PLAYER_ID),
    NOT_PLAYING_REASON TEXT,
    NOT_PLAYING_DESCRIPTION TEXT,
    PRIMARY KEY (GAME_ID, PLAYER_ID)
);

CREATE TABLE NBA24_25.GAME_EVENTS(
    GAME_ID VARCHAR(20)REFERENCES NBA24_25.NBA_GAMES(GAME_ID),
    EVENT_ID VARCHAR(20),
    PLAYER_ID VARCHAR(20) REFERENCES NBA24_25.ACTIVE_NBA_PLAYERS(PLAYER_ID),
    CURRENT_PERIOD SMALLINT,
    MINUTES_REMAINING INT,
    SECONDS_REMAINING INT,
    LOC_X INT,
    LOC_Y INT,
    SHOT_ATTEMPTED SMALLINT,
    SHOT_MADE SMALLINT,
    PRIMARY KEY (GAME_ID, EVENT_ID, PLAYER_ID)
);

CREATE TABLE NBA24_25.SHOT_DISTANCE(
    LOC_X INT,
    LOC_Y INT,
    SHOT_DISTANCE INT,
    PRIMARY KEY (LOC_X, LOC_Y)
);

CREATE TABLE NBA24_25.SHOT_TYPE(
    LOC_X INT,
    LOC_Y INT,
    SHOT_TYPE VARCHAR(30),
    PRIMARY KEY (LOC_X, LOC_Y)
);

CREATE TABLE NBA24_25.SHOT_ZONE_RANGE(
    LOC_X INT,
    LOC_Y INT,
    SHOT_ZONE_RANGE VARCHAR(30),
    PRIMARY KEY (LOC_X, LOC_Y)
);

CREATE TABLE NBA24_25.SHOT_ZONE_AREA(
    LOC_X INT,
    LOC_Y INT,
    SHOT_ZONE_AREA VARCHAR(30),
    PRIMARY KEY (LOC_X, LOC_Y)
);


CREATE TABLE NBA24_25.SHOT_ZONE_BASIC(
    LOC_X INT,
    LOC_Y INT,
    SHOT_ZONE_BASIC VARCHAR(30),
    PRIMARY KEY (LOC_X, LOC_Y)
);

CREATE VIEW NBA24_25.BOXSCORES_COMPUTED AS (
    SELECT 
        b.game_id,
        b.player_id,
        ROUND(CAST(b.fgm AS DECIMAL(5,2)) / NULLIF(b.fga, 0),2) AS FG_PCT,
        ROUND(CAST(b.fg3m AS DECIMAL(5,2)) / NULLIF(b.fg3a, 0),2) AS FG3_PCT,
        ROUND(CAST(b.ftm AS DECIMAL(5,2)) / NULLIF(b.fta, 0),2) AS FT_PCT,
        b.oreb + b.dreb AS REB,
        (b.fg3m * 3) + (b.fg2m * 2) + b.ftm AS PTS  
    FROM NBA24_25.boxscores b
);

CREATE VIEW NBA24_25.NBA_GAMES_TEAM_STATS_COMPUTED AS (
    SELECT 
        t.game_id,
        t.team_id,
        ROUND(CAST(t.fgm AS DECIMAL(5,2)) / NULLIF(t.fga, 0),2) AS FG_PCT,
        ROUND(CAST(t.fg3m AS DECIMAL(5,2)) / NULLIF(t.fg3a, 0),2) AS FG3_PCT,
        ROUND(CAST(t.ftm AS DECIMAL(5,2)) / NULLIF(t.fta, 0),2) AS FT_PCT,
        t.oreb + t.dreb AS REB,
        (t.fg3m * 3) + (t.fgm-t.fg3m * 2) + t.ftm AS PTS  
    FROM NBA24_25.nba_games_team_stats t
);