CREATE SCHEMA IF NOT EXISTS NBA24_25_S;

CREATE TABLE NBA24_25_S.NBATEAMS_S(
    TEAM_ID VARCHAR(20) PRIMARY KEY,
    FULL_NAME VARCHAR(50) NOT NULL,
    ABBREVIATION VARCHAR(10) NOT NULL,
    NICKNAME VARCHAR(20) NOT NULL,
    YEAR_FOUNDED INT,
    TEAM_CITY VARCHAR(20) NOT NULL,
    TEAM_STATE VARCHAR(20) NOT NULL,
    TEAM_URL_LOGO TEXT NOT NULL
);

CREATE TABLE NBA24_25_S.NBA_GAMES_S(
    GAME_ID VARCHAR(20) PRIMARY KEY,
    GAME_DATE DATE NOT NULL,
    HOME_TEAM_ID VARCHAR(20) NOT NULL REFERENCES NBA24_25_S.NBATEAMS_S(TEAM_ID),
    VISITING_TEAM_ID VARCHAR(20) NOT NULL REFERENCES NBA24_25_S.NBATEAMS_S(TEAM_ID) 
);

CREATE TABLE NBA24_25_S.ACTIVE_NBA_PLAYERS_S(
    PLAYER_ID VARCHAR(20) PRIMARY KEY,
    TEAM_ID VARCHAR(20) NOT NULL REFERENCES NBA24_25_S.NBATEAMS_S(TEAM_ID),
    PLAYER_LAST_NAME VARCHAR(20),
    PLAYER_FIRST_NAME VARCHAR(20),
    JERSEY_NUMBER VARCHAR(5),
    POSITION VARCHAR(20),
    PLAYER_HEIGHT VARCHAR(20),
    PLAYER_WEIGHT VARCHAR(20),
    COLLEGE VARCHAR(40),
    COUNTRY VARCHAR(50),
    DRAFT_YEAR SMALLINT,
    DRAFT_ROUND SMALLINT,
    DRAFT_NUMBER SMALLINT,
    PTS NUMERIC(5,3),
    REB NUMERIC(5,3),
    AST NUMERIC(5,3),
    PLAYER_PICTURE_URL TEXT NOT NULL
);



CREATE TABLE NBA24_25_S.NBA_GAMES_TEAM_STATS_S(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25_S.NBA_GAMES_S(GAME_ID),
    TEAM_ID VARCHAR(20) REFERENCES NBA24_25_S.NBATEAMS_S(TEAM_ID),
    WL VARCHAR(10),
    MIN INT,
    FGM SMALLINT,
    FGA SMALLINT,
    FG_PCT REAL,
    FG3M SMALLINT,
    FG3A SMALLINT,
    FG3_PCT REAL,
    FTM SMALLINT,
    FTA SMALLINT,
    FT_PCT REAL,
    OREB SMALLINT,
    DREB SMALLINT,
    REB SMALLINT,
    AST SMALLINT,
    STL SMALLINT,
    BLK SMALLINT,
    PF SMALLINT,
    PTS SMALLINT,
    PLUS_MINUS SMALLINT,
    PRIMARY KEY (GAME_ID, TEAM_ID)
);



CREATE TABLE NBA24_25_S.PLAY_BY_PLAY_SCORE_S(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25_S.NBA_GAMES_S(GAME_ID),
    CURRENT_PERIOD SMALLINT,
    TIME_LEFT VARCHAR(25),
    HTM_PTS INT,
    VTM_PTS INT,
    PRIMARY KEY(GAME_ID, CURRENT_PERIOD, TIME_LEFT,HTM_PTS,VTM_PTS) 
);

CREATE TABLE NBA24_25_S.BOXSCORES_S(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25_S.NBA_GAMES_S(GAME_ID),
    PLAYER_ID VARCHAR(20) REFERENCES NBA24_25_S.ACTIVE_NBA_PLAYERS_S(PLAYER_ID),
    STARTER SMALLINT,
    PLAYED SMALLINT,
    ASSISTS SMALLINT,
    BLOCKS SMALLINT,
    BLOCKS_RECEIVED SMALLINT,
    FGM SMALLINT,
    FGA SMALLINT,
    FG_PCT REAL,
    FOULS_OFFENSIVE SMALLINT,
    FOULS_DRAWN SMALLINT,
    FOULS_PERSONAL SMALLINT,
    FOULS_TECHNICAL SMALLINT,
    FTM SMALLINT,
    FTA SMALLINT,
    FT_PCT REAL,
    MINUTES_PLAYED VARCHAR(20),
    PLUS_MINUS SMALLINT,
    POINTS_FAST_BREAK SMALLINT,
    POINTS_IN_PAINT SMALLINT,
    POINTS_SECOND_CHANCE SMALLINT,
    PTS SMALLINT,
    OREB SMALLINT,
    DREB SMALLINT,
    REB SMALLINT,
    STL SMALLINT,
    FG3M SMALLINT,
    FG3A SMALLINT,
    FG3_PCT REAL,
    TURNOVERS SMALLINT,
    FG2M SMALLINT,
    FG2A SMALLINT,
    FG2_PCT REAL,
    HOMEORAWAY VARCHAR(5),
    PRIMARY KEY (GAME_ID, PLAYER_ID)
);


CREATE TABLE NBA24_25_S.INJURY_REPORT_S(
    GAME_ID VARCHAR(20) REFERENCES NBA24_25_S.NBA_GAMES_S(GAME_ID),
    PLAYER_ID VARCHAR(20) REFERENCES NBA24_25_S.ACTIVE_NBA_PLAYERS_S(PLAYER_ID),
    NOT_PLAYING_REASON TEXT,
    NOT_PLAYING_DESCRIPTION TEXT,
    PRIMARY KEY (GAME_ID, PLAYER_ID)
);

